services:
  - type: web
    name: afrobot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python afrobot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false